/**
 * Single Source of Truth for all UI Text, Labels, and Metric Tooltip Explanations
 * Zero dependencies, 100% type-safe with full autocomplete.
 */

export const UI_TEXT = {
  app: {
    title: 'FPL Squad Planner',
    season: '26/27',
    enterPinOrImport: 'Enter PIN or Import Team',
    views: {
      pitch: 'Pitch',
      matrix: 'Stats Matrix',
      rotation: 'Rotation Radar',
      analytics: 'AI Performance',
      pitchTooltip: 'Visual Pitch View',
      matrixTooltip: 'Player Projections & Metrics Matrix',
      rotationTooltip: 'Pre-Deadline Lineup & Rotation Risk Radar',
      analyticsTooltip: 'AI Backtest, Season Alpha & Decision Analyzer',
    },
  },
  common: {
    buy: 'Buy',
    sell: 'Sell',
    swap: 'Sub',
    captain: 'Captain',
    viceCaptain: 'Vice Captain',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    none: 'None',
    pointsShort: 'pts',
    avg: 'avg',
  },
  telemetry: {
    freeTransfers: 'Free Transfers',
    inTheBank: 'In The Bank',
    gwProjectedXp: 'GW Projected xP',
    projectedForm: 'Projected Form',
    strategy: 'Strategy',
    noChipActive: 'No Chip Active',
    ratingBadge: (pct: number) => `${pct}% Rating`,
    actualScoreBadge: (pts: number) => `(Actual: ${pts} pts)`,
    detailedRating: (d: number, m: number, f: number) => `(D:${d}% M:${m}% F:${f}%)`,
  },
  gameweekStepper: {
    gwLabel: (gw: number) => `GW ${gw}`,
    completed: 'Completed',
    planned: 'Planned',
    global: 'Global',
    prevTooltip: 'Previous Gameweek',
    nextTooltip: 'Next Gameweek',
    matrixDisabledTooltip: 'Gameweek selection disabled in Stats Matrix',
  },
  tooltips: {
    player: 'Player Name, Position and Club',
    pos: 'Player Position (GKP, DEF, MID, FWD)',
    price: 'Current player market price in millions (£m)',
    mins: 'Total minutes played on pitch this season',
    xg: 'Expected Goals — statistical measure of the quality and probability of scoring chances',
    threat: 'Official FPL Threat — gauge of player goal threat and penalty box danger',
    goals: 'Total actual goals scored this season',
    xgi: 'Expected Goal Involvement — combined probability of scoring or assisting (xG + xA)',
    points: 'Total official FPL points scored so far this season',
    xa: 'Expected Assists — probability that a pass will lead directly to a goal',
    creativity: 'Official FPL Creativity — frequency and quality of chance creation for teammates',
    assists: 'Total actual assists awarded this season',
    xgc: 'Expected Goals Conceded — defensive metric measuring opponent scoring danger',
    cs: 'Clean Sheets — matches where the team conceded 0 goals (while player played 60+ minutes)',
    xp: 'AI Projected Points for the selected Gameweek (OpenFPL Machine Learning)',
    horizonXp: 'Cumulative AI Projected Points across the selected Gameweek horizon',
    form: 'Official FPL Form — average points scored per match over the last 30 days',
    bps: 'Bonus Points System score — match activity metric determining 3, 2, 1 bonus points',
    transfersToday: 'Net transfers in/out during the current 24-hour daily cycle',
    velocity: 'Hourly transfer rate speed (% progress per hour towards price threshold)',
    targetProgress: 'Percentage progress towards overnight price rise (+100%) or fall (-100%) threshold',
    timing: 'Estimated timing when price change is forecasted to trigger (e.g. Tonight, Tomorrow)',
    prediction: 'AI Price prediction status (Rising, Falling, Approaching, Stable)',
    action: 'Quick transfer scout and detail actions',
    // Category Group Headers
    categories: {
      playerInfo: 'Player identity, club, position, pricing and match minutes',
      goalThreat: 'Underlying attacking shooting metrics, expected goals & goal conversion',
      involvement: 'Overall offensive involvement (xG + xA) and total season points',
      creativity: 'Key passes, expected assists, and chance creation for teammates',
      defensive: 'Defensive security, expected goals conceded (xGC) and clean sheet equity',
      aiProjections: 'OpenFPL Bayesian Expected Points (xP) ML projections',
      form: 'Average points scored per match over the last 30 days',
      action: 'Direct transfer scout and player detail modal actions',
    },
  },
  analytics: {
    title: 'AI Performance & Season Alpha',
    subtitle: 'Backtesting OpenFPL Machine Learning recommendations vs. your actual decisions throughout the season.',
    badges: {
      aiAlpha: 'Net AI Alpha',
      actualTotal: 'Actual Points',
      simulatedTotal: 'AI Co-Pilot Points',
      rankProjection: 'Projected Overall Rank',
      pointsDelta: (delta: number) => `${delta >= 0 ? '+' : ''}${delta} pts`,
    },
    sections: {
      driftTitle: 'Season Trajectory Drift Curve',
      driftSubtitle: 'Cumulative points: Your Actual Team vs. AI Co-Pilot Simulation',
      captainTitle: 'The Captaincy Alpha (Armband Analyzer)',
      captainSubtitle: 'Points comparison between your chosen captain vs. OpenFPL AI Top Captain projection',
      attributionTitle: 'Points Attribution Breakdown',
      attributionSubtitle: 'Decomposing where the AI algorithmic edge originated across the pitch',
      transfersTitle: 'Transfer Decision Matrix',
      transfersSubtitle: 'Comparing your actual weekly transfers against the AI #1 recommended move',
    },
    attribution: {
      cleanSheets: 'Clean Sheet Equity',
      cleanSheetsDesc: 'Points gained from defensive hazard & opponent clean sheet probability models',
      goals: 'Goal Threat Conversion',
      goalsDesc: 'Attacking points captured via xG volume and high-quality box chances',
      assists: 'Creativity & Assist Return',
      assistsDesc: 'Value gained from designated set-piece tracking and open-play xA playmakers',
      bonus: 'BPS Magnetism',
      bonusDesc: 'Bonus points captured by OpenFPL baseline BPS regression algorithms',
      teamValue: 'Price Radar Team Value',
      teamValueDesc: 'Extra budget unlocked by beating overnight transfer market price changes',
    },
  },
  mlLab: {
    bannerTag: 'Factorial ML Laboratory',
    activeArmsBadge: (count: number) => `${count} Active Experimental Arms`,
    title: 'Multi-Armed Machine Learning Arena',
    subtitle: 'Testing cutting-edge quantitative signals in isolated experimental arms alongside the Production baseline without risking live squad plans.',
    exitLab: 'Exit Lab Mode',
    tabs: {
      arms: '🔬 Experimental Arms Leaderboard',
      divergences: '⚡ Key Model Disagreements',
      architecture: '🏛️ Factorial Design',
    },
    armsSection: {
      testedScope: 'Tested Scope:',
      armMaeVsProd: 'Arm MAE vs Prod:',
    },
    divergencesSection: {
      title: 'Upcoming GW Key Model Disagreements',
      subtitle: 'Players where the experimental arms diverge most significantly from the Production baseline:',
      prodVsExp: 'Prod vs. Experimental',
    },
    architectureSection: {
      title: 'Factorial Experimentation Methodology',
      description: 'In quantitative sports modeling, testing multiple variables inside a single black box leads to confounding errors. We isolate each hypothesis into its own independent mathematical arm. Each week, we calculate out-of-sample MAE error deltas against actual match events to scientifically prove which signals add true predictive alpha.',
    },
  },
  rotationRisk: {
    title: 'Lineup & Rotation Risk Radar',
    subtitle: 'Pre-deadline starting certainty, sub-risk analysis, and manager rotation hazard indicators.',
    badges: {
      highRisk: 'High Bench Risk',
      mediumRisk: 'Rotation / Sub Risk',
      doubtful: 'Injury Doubt',
      fatigueRisk: 'European Fatigue',
      safe: 'Nailed Starter',
      startProbability: (pct: number) => `${pct}% Start Chance`,
    },
    detailModal: {
      sectionTitle: 'Starting Certainty & Rotation Risk Analysis',
      officialQuoteLabel: 'Official Press Conference Quote',
      aiVerdictLabel: 'AI Algorithmic Verdict',
      estimatedMinutesLabel: 'Expected Minutes on Pitch',
    },
    reasons: {
      managingLoad: "Manager is managing player load; high risk of being rested or subbed at 60'.",
      tightness: 'Muscle tightness reported in training; elevated risk of early substitution or benching.',
      lateFitnessTest: 'Subject to a late pre-match fitness test; starting spot is unconfirmed.',
      assessed: 'Undergoing medical assessment ahead of the weekend fixture.',
      illness: 'Recovering from illness; stamina and match fitness being evaluated.',
      knock: 'Suffered a minor knock in the previous match; being monitored by physios.',
      europeanFatigue: 'Played 90 minutes in European competition midweek (<72h recovery turnaround).',
      pepRoulette: 'High manager rotation volatility detected for this tactical position.',
      defaultDoubtful: 'Flagged with questionable status in official FPL injury reports.',
      defaultSafe: 'Nailed starting regular with optimal physical recovery and zero fitness flags.',
    },
  },
} as const;

