/**
 * Single Source of Truth for all UI Text, Labels, and Metric Tooltip Explanations
 * Zero dependencies, 100% type-safe with full autocomplete.
 */

export const UI_TEXT = {
  app: {
    title: 'FPL Squad Planner',
    season: '26/27',
    enterPinOrImport: 'Enter PIN or Import Team',
    views: {
      pitch: 'Pitch',
      matrix: 'Stats Matrix',
      analytics: 'AI Performance',
      pitchTooltip: 'Visual Pitch View',
      matrixTooltip: 'Player Projections & Metrics Matrix',
      analyticsTooltip: 'AI Backtest, Season Alpha & Decision Analyzer',
    },
  },
  common: {
    buy: 'Buy',
    sell: 'Sell',
    swap: 'Sub',
    captain: 'Captain',
    viceCaptain: 'Vice Captain',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    none: 'None',
    pointsShort: 'pts',
    avg: 'avg',
  },
  telemetry: {
    freeTransfers: 'Free Transfers',
    inTheBank: 'In The Bank',
    gwProjectedXp: 'GW Projected xP',
    projectedForm: 'Projected Form',
    strategy: 'Strategy',
    noChipActive: 'No Chip Active',
    ratingBadge: (pct: number) => `${pct}% Rating`,
    actualScoreBadge: (pts: number) => `(Actual: ${pts} pts)`,
    seasonTotalBadge: (pts: number) => `(Season Total: ${pts} pts)`,
    detailedRating: (d: number, m: number, f: number) => `(D:${d}% M:${m}% F:${f}%)`,
  },
  gameweekStepper: {
    gwLabel: (gw: number) => `GW ${gw}`,
    completed: 'Completed',
    planned: 'Planned',
    global: 'Global',
    prevTooltip: 'Previous Gameweek',
    nextTooltip: 'Next Gameweek',
    matrixDisabledTooltip: 'Gameweek selection disabled in Stats Matrix',
  },
  tooltips: {
    player: 'Player Name, Position and Club',
    pos: 'Player Position (GKP, DEF, MID, FWD)',
    price: 'Current player market price in millions (£m)',
    mins: 'Total minutes played on pitch this season',
    xg: 'Expected Goals — statistical measure of the quality and probability of scoring chances',
    threat: 'Official FPL Threat — gauge of player goal threat and penalty box danger',
    goals: 'Total actual goals scored this season',
    xgi: 'Expected Goal Involvement — combined probability of scoring or assisting (xG + xA)',
    points: 'Total official FPL points scored so far this season',
    xa: 'Expected Assists — probability that a pass will lead directly to a goal',
    creativity: 'Official FPL Creativity — frequency and quality of chance creation for teammates',
    assists: 'Total actual assists awarded this season',
    xgc: 'Expected Goals Conceded — defensive metric measuring opponent scoring danger',
    cs: 'Clean Sheets — matches where the team conceded 0 goals (while player played 60+ minutes)',
    xp: 'AI Projected Points for the selected Gameweek (OpenFPL Machine Learning)',
    horizonXp: 'Cumulative AI Projected Points across the selected Gameweek horizon',
    form: 'Official FPL Form — average points scored per match over the last 30 days',
    bps: 'Bonus Points System score — match activity metric determining 3, 2, 1 bonus points',
    transfersToday: 'Net transfers in/out during the current 24-hour daily cycle',
    velocity: 'Hourly transfer rate speed (% progress per hour towards price threshold)',
    targetProgress: 'Percentage progress towards overnight price rise (+100%) or fall (-100%) threshold',
    timing: 'Estimated timing when price change is forecasted to trigger (e.g. Tonight, Tomorrow)',
    prediction: 'AI Price prediction status (Rising, Falling, Approaching, Stable)',
    action: 'Quick transfer scout and detail actions',
    // Category Group Headers
    categories: {
      playerInfo: 'Player identity, club, position, pricing and match minutes',
      goalThreat: 'Underlying attacking shooting metrics, expected goals & goal conversion',
      involvement: 'Overall offensive involvement (xG + xA) and total season points',
      creativity: 'Key passes, expected assists, and chance creation for teammates',
      defensive: 'Defensive security, expected goals conceded (xGC) and clean sheet equity',
      aiProjections: 'OpenFPL Bayesian Expected Points (xP) ML projections',
      form: 'Average points scored per match over the last 30 days',
      action: 'Direct transfer scout and player detail modal actions',
    },
  },
  analytics: {
    title: 'AI Performance & Season Alpha',
    subtitle: 'Backtesting OpenFPL Machine Learning recommendations vs. your actual decisions throughout the season.',
    badges: {
      aiAlpha: 'Net AI Alpha',
      actualTotal: 'Actual Points',
      simulatedTotal: 'AI Co-Pilot Points',
      rankProjection: 'Projected Overall Rank',
      pointsDelta: (delta: number) => `${delta >= 0 ? '+' : ''}${delta} pts`,
    },
    sections: {
      driftTitle: 'Season Trajectory Drift Curve',
      driftSubtitle: 'Cumulative points: Your Actual Team vs. AI Co-Pilot Simulation',
      captainTitle: 'The Captaincy Alpha (Armband Analyzer)',
      captainSubtitle: 'Points comparison between your chosen captain vs. OpenFPL AI Top Captain projection',
      attributionTitle: 'Points Attribution Breakdown',
      attributionSubtitle: 'Decomposing where the AI algorithmic edge originated across the pitch',
      transfersTitle: 'Transfer Decision Matrix',
      transfersSubtitle: 'Comparing your actual weekly transfers against the AI #1 recommended move',
    },
    attribution: {
      cleanSheets: 'Clean Sheet Equity',
      cleanSheetsDesc: 'Points gained from defensive hazard & opponent clean sheet probability models',
      goals: 'Goal Threat Conversion',
      goalsDesc: 'Attacking points captured via xG volume and high-quality box chances',
      assists: 'Creativity & Assist Return',
      assistsDesc: 'Value gained from designated set-piece tracking and open-play xA playmakers',
      bonus: 'BPS Magnetism',
      bonusDesc: 'Bonus points captured by OpenFPL baseline BPS regression algorithms',
      teamValue: 'Price Radar Team Value',
      teamValueDesc: 'Extra budget unlocked by beating overnight transfer market price changes',
    },
  },
} as const;

